# image: /home/grl/barn_ws/src/jackal_helper/worlds/BARN/map_files/map_pgm_0.pgm
image: maps/map_pgm_50.pgm
resolution: 0.15
origin: [-4.5, 0.0, 0.0]
occupied_thresh: 0.65
free_thresh: 0.196
negate: 1